# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

desc '[CI]Runs the PR review'
lane :review do
  if Helper.is_ci?
    gradle(task: 'lint')
    danger(
      danger_id: 'danger',
      dangerfile: 'Dangerfile',
      github_api_token: ENV['GITHUB_API_TOKEN'],
      verbose: true
    )
  end
end

desc 'Runs all the tests'
lane :test do
  gradle(task: 'lint')
end

