# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

before_all do |lane, options|
  ENV['JAVA_HOME'] = '/usr/lib/jvm/java-11-openjdk-amd64' if Helper.is_ci?
end

desc "Runs all the tests"
lane :test do
  install_android_studio
  gradle(task: "lint")
  Dir.chdir('../')
  workspace = Dir.pwd
  android_studio_path =
          ENV['ANDROID_STUDIO_HOME'] ||
            '/Applications/Android Studio.app/Contents'
  FileUtils.rm_rf("#{workspace}/fastlane/inspect")
  sh("#{android_studio_path}/bin/inspect.sh #{workspace} #{workspace}/fastlane/inspect.xml #{workspace}/fastlane/inspect")
  sh("ls -al #{workspace}/fastlane/inspect")
end

private_lane :install_android_studio do
  unless File.exists?('/opt/android-studio')
    sh(
      'curl -o /opt/android-studio.tar.gz -OL https://redirector.gvt1.com/edgedl/android/studio/ide-zips/2020.3.1.23/android-studio-2020.3.1.23-linux.tar.gz'
    )
    sh('tar -zxvf /opt/android-studio.tar.gz -C /opt')
  end
  ENV['ANDROID_STUDIO_HOME'] = '/opt/android-studio'
end

